baseURL = "https://elprofesorkaz.github.io/lacaraocultadelhacker.github.io/"
relativeURLs = true
languageCode = 'es-es'
title = 'LA CARA OCULTA DEL HACKER'
theme = 'terminal'

[params]
  # Diseño de la terminal (podemos cambiarlo a azul o naranja luego si prefieres)
  terminalTheme = "green"
  
  # Subtítulo que aparecerá en la página principal
  subtitle = "Lo que no te cuentan en los manuales oficiales de Ciberseguridad."
